language: generic 
sudo: required
services:
    - docker
    
before_install:
    - docker build -t bpanneer/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true bpanneer/docker-react npm run test